---
- name: Stop all active nodes
  hosts: localhost
  gather_facts: false

  tasks:
    - name: get ec2 instance info of running nodes. 
      ec2_instance_info:
        filters:
          instance-state-name: ["running"]
        region: us-east-1
      register: ec2_info

    - name: Print details of ec2_info
      ansible.builtin.debug:
        msg:  "Instance: {{ item.tags.Name }} is {{ item.state.name }}. "
      loop: "{{ ec2_info['instances'] }}"
      loop_control:
        label: "{{ item.tags.Name }}"

    - name: stop all 
      ec2_instance:
        instance_ids: "{{item.instance_id}}"
        region: us-east-1
        state: stopped
        wait: yes
      with_items: "{{ec2_info.instances}}"

    - name: get ec2 instance info after stop 
      ec2_instance_info:
        region: us-east-1
      register: ec2_info_post

    - name: Print details of instance_info of all nodes
      ansible.builtin.debug:
        msg:  "Instance: {{ item.tags.Name }} is {{ item.state.name }}. "
      loop: "{{ ec2_info_post['instances'] }}"
      loop_control:
        label: "{{ item.tags.Name }}"


