---
- name: Get state of node from ec2_instance_info
  hosts: localhost
  gather_facts: false

  tasks:
    - name: get ec2 instance info
      ec2_instance_info:
        region: us-east-1
      register: ec2_info
    

    - name: Print details of ec2_info
      ansible.builtin.debug:
        msg: "{{ ec2_info }}"

